### ISSUE TITLE
Spam kick on running coreprotect queries ingame

### ISSUE THREAD

**Issue by DidsheMa** [DaMarine/Slabserver-Bugs#20] opened 2020-06-20 21:05 UTC
**Describe the bug**
Mods get kicked for spamming on running lengthier coreprotect database queries

**To Reproduce**
Steps to reproduce the behaviour:
1. Be not exempt from getting kicked for spamming and have coreprotect access
2. Run a /co lookup with a time interval longer than a few hours that likely returns a fair bunch of results
3. Get booted

**Expected behaviour**
To not get booted on running queries I guess

**Additional context**
Probably a venturechat setting somewhere?

**Comment by DidsheMa** [comment] 2020-06-25 17:42
Not consistently reproducable, hasn't happened in a while now (even when asking for it). Possibly TPS related? No clue, but I guess this is as low prio as it gets then.

**Comment by DaMarine** [comment] 2020-06-25 19:52
Very strange indeed. I'll take a second pass at the logs and try to see what could have caused this.

**Comment by Frogperson** [comment] 2020-07-05 22:49
I've added `/co` to the spam exclusion list in spigot.yml. Not sure if it'll fix it or not, but I guess we'll see

**Comment by DaMarine** [comment] 2020-08-03 21:51
I don't believe this has been reproduced since, closing

**Comment by DidsheMa** [comment] 2020-10-13 20:56
Just got kicked again, reopening (was using the little arrows in the coreprotect responses to flip resultset pages)

I'll have another look to try and find a fix

**Comment by Frogperson** [comment] 2020-10-17 14:08
Is this from one lookup command, or from you running multiple commands? 
![image](https://user-images.githubusercontent.com/17440180/96339027-d4058080-105f-11eb-8f3d-9d33c4038b37.png)

Each time you click the arrow it'll run a command, and thus clicking too fast will spam them. If you're xray checking or just trying to populate Watson with data, then I highly recommend using `/co l 1:1000` as it'll drastically reduce the amount of pages you have to go through.

**Comment by DidsheMa** [comment] 2020-10-17 16:17
True, I generally do use l 1:1000 for xray checking - this is more relevant for on the fly use cases like chest transactions.
I'm aware that clicking the arrows in quick succession "spams" the commands and usually try and follow best practice; I would appreciate not getting kicked for spam if I ever don't regardless though

**Comment by Frogperson** [comment] 2020-10-19 14:49
I'm not really sure why you're still even getting kicked for the spam though, because `/co` has been added to the spam-exclusions list. Do we need `/co l` instead maybe?

> Side note, I haven't gotten Watson to properly work in our current environment, and I believe I'm not the only one

What problems are you guys still having? I had some initial issues especially with the teleport command but eventually got everything working. Watson still gets updated every few weeks or so, so I'd recommend trying out the latest version to see if the issues are fixed https://www.curseforge.com/minecraft/mc-mods/watson

**Comment by DidsheMa** [comment] 2020-10-20 11:42
Aye, if I remember correctly it was only the teleport that was acting up, good chance their releases have fixed it by now. I don't really see the need for Watson now that Coreprotect can also do the teleports tbh, but I'll try get it running again later today, if only as a test

As for the spam kick - In which config is the spam exclusions list? Is it a vanilla thing? Tried looking in bukkit and paper.ymls but couldn't find it... and yeah maybe /co l or /co * would do the trick, no idea honestly... My first suspect was Venturechat, but its spam protection is properly disabled on the paper servers. Could it have something to do with enable_bungeecord_muting in the Bungee VC config? Grasping at straws here, but I couldn't find what else that is supposed to do, so might be worth a try too ¯\_(ツ)_/¯ (but I doubt it's related honestly)

**Comment by DaMarine** [comment] 2020-10-21 19:48
I've added `/co l` and `/co *` to the exclusion list too, but in checking it seems that `/co` wasn't in the exclusion list for the RW, which could have been the reason you saw this issue again Didy. Either way, I'm hoping one of these changes may have fixed it now.

**Closed** 2021-02-07 21:49 UTC
Labels: bug
