### ISSUE TITLE
No health bar display in RW tab list

### ISSUE THREAD

**Issue by DidsheMa** [DaMarine/Slabserver-Bugs#49] opened 2022-02-08 14:25 UTC
Description:
- No health bar is displayed in the tab list in the resource world
- RW players show up as full health on main server tablist, regardless of their health status

Expected behaviour:
- Health bar display is shared fully across both tablists, and updated according to player health status

This is despite matching TAB config.yml on both Paper servers, and the proxy's TAB config seemingly being correctly set according to https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Yellow-number

**Comment by DidsheMa** [comment] 2022-02-08 14:31
I've now tried explicitly setting 
```
yellow-number-in-tablist:
  enabled: true
  value: '%player_health%'
```
instead of 
`yellow-number-in-tablist: '%player_health%'`
on RW, despite the latter seeming to be sufficient in main survival - will keep an eye after next restart

**Comment by DaMarine** [comment] 2022-05-03 21:13
We'll use the test env that can be produced from #155 to tackle this properly, rather than trying to debug in prod - will pick this up once that is complete

**Comment by chrissamael** [comment] 2022-05-04 09:14
The changes to TAB are set on the proxy, after some tinkering with its config.yml I have managed to reactivate the health bars
after updating, I noticed this being spammed in the error.log:
`[TAB v3.0.1] yellow number only accepts numeric values! (Attempted to use "%health%")`

So I had another look at the yellow number setting, and noticed `disable-in-worlds` was set to `null`. Changed that up into: 
```yml
yellow-number-in-tablist:
  enabled: true
  value: '%player_health%'
  disable-in-worlds: 
  - disabledworld
  disable-in-servers:
  - disabledserver
 ```

 reloaded the TAB plugin with `btab reload` on the proxy and it's working as intended again :)

**Comment by DaMarine** [comment] 2022-05-04 11:52
It's a beautiful sight to see these back, closing!

**Closed by DaMarine** 2022-05-04 11:52 UTC
