### ISSUE TITLE
Players can disappear from the Tab list when reconnecting too quickly

### ISSUE THREAD

**Issue by GoldenDelicios** [DaMarine/Slabserver-Bugs#45] opened 2021-10-13 05:27 UTC
Players who connect and disconnect then reconnect again in a short period of time can mislead our current plugins to believe a player is offline when they are not.
e.g.
```
BoooshXe joined the server
BoooshXe joined the server
BoooshXe left the server
```

Easiest way to reproduce:
1. Launch two Minecraft clients logged onto the same account
2. Join Slabserver on both clients as quickly as possible
3. One client will log in first, then be promptly kicked off by the joining of the other client. If the issue occurs, you will not be visible on the Tab list.

**Comment by GoldenDelicios** [comment] 2021-11-08 01:15
November update:
- Look for potential sources of this issue
- Consider whether joins can be counted during join events (instead of pre-login events)
- Consider "hacky" fixes like re-populating player list every time, or using a join/leave counter

**Comment by GoldenDelicios** [comment] 2021-12-05 19:21
The tab list issue probably requires submitting an issue to the developer. The chat message issue is probably related to #39; I've noticed the issues don't necessarily appear simultaneously.

The issue seems to be that `PlayerDisconnectEvent` does not necessarily precede a `ServerSwitchEvent` (representing a new join), however a `ServerDisconnectEvent` does. So changing [`BungeeEventListener#onQuit`](https://github.com/NEZNAMY/TAB/blob/master/bungeecord/src/main/java/me/neznamy/tab/platforms/bungeecord/BungeeEventListener.java#L29) to use `ServerDisconnectEvent` instead of `PlayerDisconnectEvent` should fix the issue.

**Comment by DaMarine** [comment] 2022-05-03 20:48
I spoke to the dev about this and they've given us a build they believe will fix this: https://github.com/NEZNAMY/TAB/issues/539

I'll do my best not to forget I did this again, and get it tested

**Comment by chrissamael** [comment] 2022-05-03 21:01
I was clicking around on the github and noticed the latest version of TAB includes the fix for this - I updated the jar on the proxy, next restart should activate it

**Comment by chrissamael** [comment] 2022-05-04 09:09
Can't reproduce issue after update, so, I'll call it fixed?

**Comment by DaMarine** [comment] 2022-05-04 11:49
Happy that's enough validation unless proved otherwise!

**Closed by DaMarine** 2022-05-04 11:49 UTC
Labels: Bug, slabserver
